### ISSUE TITLE
Auto renew ?

### ISSUE THREAD

**Issue by picanl** [txthinking/nico#1]
Does it auto renew certificates when running?

**Comment by txthinking** [comment]
Yes

**Comment by picanl** [comment]
ah great!

i'm trying to build it myself with build.sh but getting 

root@test:~/build/nico# ./build.sh version
go: cannot find main module, but found .git/config in /root/build/nico
        to create a module there, run:
        go mod init

**Comment by txthinking** [comment]
why don't use pre build binary? Or need another custom feature?

**Comment by picanl** [comment]
yes but got it, will create a merge request
