### ISSUE TITLE
讀取 config文件？

### ISSUE THREAD

**Issue by changchichung** [txthinking/nico#10]
請問可以支援config文件嗎？
依照指定格式設定文件，然後執行nico 的時候可以下參數指定去讀取config
不然路徑多的時候，管起來有點麻煩

**Comment by txthinking** [comment]
如果要额外增加一个文件的话，是否可以用 `sh` 文件替代，sh 文件里一个命令可以分割位多行用 `\`连接。同时又不必额外掌握一种配置文件语法

```
touch a.sh
chmod +x a.sh
```
```
cat a.sh
```
```
./nico \
    a.com http://127.0.0.1:80 \
    b.com http://127.0.0.1:81 \
    c.com /web/root/www1 \
    d.com /web/root/www2
```
```
./a.sh
```

**Comment by txthinking** [comment]
> 碰到多個域名、多個目錄要轉址的時候，要修改、要刪除就比較麻煩

这个怎么理解，可以举个例子吗

> 而且不適合用supervisor/systemd 之類的軟體去啟動

目前在结合 joker 用。这个的确有道理了，supervisor/systemd 结合用的话的确指定个配置文件方便修改。会认真考虑这个提议

**Comment by donxv** [comment]
> > 碰到多個域名、多個目錄要轉址的時候，要修改、要刪除就比較麻煩
> 
> 这个怎么理解，可以举个例子吗
> 
> > 而且不適合用supervisor/systemd 之類的軟體去啟動
> 
> 目前在结合 joker 用。这个的确有道理了，supervisor/systemd 结合用的话的确指定个配置文件方便修改。会认真考虑这个提议

关于 nico 结合 joker：

如果将nico写成sh，使用
`joker nico.sh`
那么
`joker list`
似乎不会添加这个进程，无法使用`joker restart`，
但是`ps | grep `可以看到

**Comment by txthinking** [comment]
把 joker 写到 nico.sh 里面去

```
cat nico.sh
```
```
joker nico \
    a.com /www/a \
    b.com /www/b \
    c.com /www/c
```
```
./nico.sh
```
这样 nico 进程就由 joker直接来fork了

**Comment by txthinking** [comment]
v20240323
